Update root Makefile to handle new KM Makefile

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -8,7 +8,9 @@ JAVAC_CP = $(shell ./bin/classpath.sh)
 JAVAC_OPTIONS =$(EXTRA_JAVAC_OPTIONS) -Xlint:none -proc:none
 ANDROID_BUILD_TOOLS = @ANDROID_BUILD_TOOLS@
 ANDROID_SDK_TOOLS = @ANDROID_SDK_TOOLS@
-AUDIT_KERNEL_MODULES_MAKEFILE = src/spade/reporter/audit/kernel-modules/Makefile
+KERNEL_MODULES ?= false
+AUDIT_KERNEL_MODULES_SRC = src/spade/reporter/audit/kernel-modules/
+AUDIT_KERNEL_MODULES_INSTALL = lib/kernel-modules
 
 #
 # In Ubuntu, when you install llvm headers, it puts llvm and llvm-c inside version folder.
@@ -28,7 +30,9 @@ OS_KERNEL_RELEASE = $(shell uname -r)
 OS_KERNEL_MAJOR = $(shell uname -r | cut -d '.' -f 1)
 OS_KERNEL_MINOR = $(shell uname -r | cut -d '.' -f 2 | xargs printf "%02d")
 OS_KERNEL_NUMBER = $(OS_KERNEL_MAJOR)$(OS_KERNEL_MINOR)
-MAX_OS_KERNEL_NUMBER = 507
+MIN_OS_KERNEL_NUMBER = 504
+MIN_OS_KERNEL_NUMBER_PRINTABLE = 5.4
+
 ifeq ($(OS_NAME), Darwin)
 	OS_BUILD = build-openbsm
 	NO_FUSE = $(shell pkg-config fuse; echo $$?)
@@ -48,11 +52,6 @@ ifeq ($(OS_NAME), Linux)
 	OS_CONFIG_PATH = /usr/lib/pkgconfig
 	REPLIB_OSFLAG = -D_LLVMREPORTER_LINUX
 	LLVM_RULE = build-linux-llvm
-endif
-
-# kernel modules build default = false
-ifndef KERNEL_MODULES
-	KERNEL_MODULES = false
 endif
 
 # -------- Default Build Configuration -----
@@ -154,15 +153,17 @@ audit-kernel-module:
 				echo 'ERROR: Kernel modules build failed. Failed to get current kernel release number.'; \
 				exit 1; \
 			else \
-				if [ $(OS_KERNEL_NUMBER) -ge $(MAX_OS_KERNEL_NUMBER) ]; then \
-					echo 'Warning: Kernel version > 5.7 uses workaround from https://github.com/xcellerator/linux_kernel_hacking/issues/3#issue-782815541 by hkerma'; \
+				if [ $(OS_KERNEL_NUMBER) -ge $(MIN_OS_KERNEL_NUMBER) ]; then \
+					echo 'Warning: Kernel module uses workaround from https://github.com/xcellerator/linux_kernel_hacking/issues/3#issue-782815541 by hkerma'; \
+					$(MAKE) --no-print-directory -C $(AUDIT_KERNEL_MODULES_SRC) all; \
+					$(MAKE) --no-print-directory -C $(AUDIT_KERNEL_MODULES_SRC) INSTALL_DIR=$(AUDIT_KERNEL_MODULES_INSTALL) install; \
 				else \
-					echo 'Building kernel modules normally'; \
+					echo 'ERROR: Kernel modules build failed. Kernel version $(shell uname -r) not greater than or equal to $(MIN_OS_KERNEL_NUMBER_PRINTABLE).'; \
+					exit 1; \
 				fi; \
-				$(MAKE) --no-print-directory -f $(AUDIT_KERNEL_MODULES_MAKEFILE); \
 			fi \
 		else \
-			$(MAKE) --no-print-directory -f $(AUDIT_KERNEL_MODULES_MAKEFILE) clean; \
+			$(MAKE) --no-print-directory -C $(AUDIT_KERNEL_MODULES_SRC) INSTALL_DIR=$(AUDIT_KERNEL_MODULES_INSTALL) clean; \
 		fi \
 	else \
 		echo 'Skipped kernel modules. OS Kernel not supported'; \
@@ -279,7 +280,7 @@ clean:
 	@rm -rf cfg/ssl
 	@rm -rf log
 	@rm -rf tmp
-	@$(MAKE) --no-print-directory -f $(AUDIT_KERNEL_MODULES_MAKEFILE) clean
+	@$(MAKE) --no-print-directory -C $(AUDIT_KERNEL_MODULES_SRC) INSTALL_DIR=$(AUDIT_KERNEL_MODULES_INSTALL) clean
  
 DESTDIR = @prefix@
 install:
